apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-tutorial
  namespace: ml-tutorial
  labels:
    app.kubernetes.io/instance: ml-tutorial
    app.kubernetes.io/name: ml-tutorial
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        - tutorial-k8s.maximilianlamm.de
      secretName: tutorial-k8s-tls
  rules:
    - host: tutorial-k8s.maximilianlamm.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-tutorial
                port:
                  number: 80
