apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "giftify-chart.fullname" .}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image2.name }}
    spec:
      containers:
        - name: giftify
          image: "{{ .Values.image2.repository }}:{{ .Values.image2.tag }}"
          ports:
            - containerPort: {{.Values.service2.port}}
          env:
            - name: PORT
              value: "{{.Values.service2.port}}"
