apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service2.name }}"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.port }}
      nodePort: {{ .Values.service2.nodePort }}
  selector:
    app: {{ .Values.image2.name }}